import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { distroName, runPowerShell } from "./wsl-host.js";

const AHK_HEADER = "; Generated by dsh-wsl-tray — requires AutoHotkey v2+";

// First match wins, so order is the priority.
//
// The WSL checkout leads deliberately. These scripts are what the recovery path
// runs when dsh will not start, and the copy they read has to be the copy that
// actually gets updated. Two checkouts of the same repository existed, edits
// landed in the one under src, and the Windows one silently drifted — far
// enough that a working relay fix was overwritten by a later sync and the loss
// only surfaced because someone went looking. Leading with the WSL path means
// the recovery runs what git has, not what a stale directory happens to hold.
//
// The Windows paths stay as fallbacks: if the WSL checkout is ever removed, a
// recovery that still works from the other copy beats one that finds nothing.
const FALLBACK_KIT_PATHS = [
  "/home/rchua/src/dsh-wsl-kit",
  "/mnt/c/Users/rchua/Desktop/AIFullStackDevelopment/dsh-wsl-kit",
  "/mnt/c/Users/rchua/Desktop/dsh-wsl-kit",
];

export function notWsl() {
  return { ok: false, error: "not running in WSL" };
}

export function parameters() {
  return {
    type: "object",
    additionalProperties: false,
    properties: {
      action: {
        type: "string",
        enum: ["status", "install_scripts", "install_tray"],
        description:
          "status = report paths; install_scripts = PS1 + desktop shortcut; install_tray = AHK v2 tray icon + PS1.",
      },
      url: { type: "string", description: "Browser URL (default http://127.0.0.1:3081 via kit relay; dsh itself listens on 3080 inside WSL)." },
      kitPath: { type: "string", description: "Override path to dsh-wsl-kit (or set DSH_WSL_KIT)." },
    },
  };
}

export function outputSchema() {
  return { type: "object", additionalProperties: true };
}

export function format(v) {
  const lines = [`wsl_tray action=${v.action || "?"} ok=${v.ok}`];
  if (v.dir) lines.push(`dir: ${v.dir}`);
  if (v.kitPath) lines.push(`kitPath: ${v.kitPath}`);
  if (v.startPs1) lines.push(`startPs1: ${v.startPs1}`);
  if (v.trayAhk) lines.push(`trayAhk: ${v.trayAhk}`);
  if (v.autohotkeyPath) lines.push(`autohotkey: ${v.autohotkeyPath}`);
  if (v.shortcutHint) lines.push(`shortcut: ${v.shortcutHint}`);
  for (const a of v.advice || []) lines.push(`- ${a}`);
  if (v.error) lines.push(`error: ${v.error}`);
  return lines.join("\n");
}

/** Resolve dsh-wsl-kit root: kitPath arg → DSH_WSL_KIT → existsSync candidates. */
export function resolveKitPath({
  kitPath = "",
  env = process.env,
  exists = existsSync,
  candidates = FALLBACK_KIT_PATHS,
} = {}) {
  const fromArg = String(kitPath || "").trim();
  if (fromArg && exists(join(fromArg, "scripts", "restart-dsh-web.sh"))) {
    return { ok: true, path: fromArg.replace(/\/+$/, ""), source: "arg" };
  }
  const fromEnv = String(env.DSH_WSL_KIT || "").trim();
  if (fromEnv && exists(join(fromEnv, "scripts", "restart-dsh-web.sh"))) {
    return { ok: true, path: fromEnv.replace(/\/+$/, ""), source: "env" };
  }
  for (const c of candidates) {
    if (exists(join(c, "scripts", "restart-dsh-web.sh"))) {
      return { ok: true, path: c.replace(/\/+$/, ""), source: "fallback" };
    }
  }
  return { ok: false, path: "", source: "missing" };
}

/**
 * A shell command as the contents of a PowerShell single-quoted string.
 *
 * The command contains single quotes of its own -- sed 's/\r$//' appears twice
 * in every one of them -- and an unescaped one ends the PowerShell string early.
 * The result is not an error but a mangled invocation: the pieces get reassembled
 * into something bash rejects or, worse, partly runs. test-path on the launcher
 * said the file existed and the file was still useless.
 *
 * PowerShell escapes a single quote inside a single-quoted string by doubling it.
 */
function psQuote(command) {
  return String(command).replace(/'/g, "''");
}

export function ps1Body(distro, url, kitPath) {
  const restart = `${kitPath}/scripts/restart-dsh-web.sh`;
  const health = `${kitPath}/scripts/check-dsh-health.sh`;
  const alive = `${kitPath}/scripts/dsh-web-alive.inc.sh`;
  // The PATH assignment is quoted, and that is load-bearing.
  //
  // wsl.exe launched from Windows appends the Windows PATH to the Linux one, so
  // $PATH here carries "/mnt/c/Program Files (x86)/cloudflared/". Unquoted, those
  // parentheses are a bash syntax error and the command line dies before the
  // first sed runs:
  //
  //   -c: line 1: syntax error near unexpected token `('
  //
  // The launcher therefore appeared to do nothing. Get-DshTokenUrl was never
  // affected because it does not touch PATH, which is why the token could be
  // read while the restart never happened.
  const bashRestart = `bash '${restart}'`;
  const bashHealth = `bash '${health}'; echo; read -n 1 -p 'Press any key...'`;
  // Bare :3081 is 401 on dsh ≥0.1.2 — never open without ?token= from /tmp/dsh-ui-url.
  return [
    "# Generated by dsh-wsl-tray — start dsh web (WSL) + localhost relay, then open token URL.",
    "# NEVER bookmark bare http://127.0.0.1:3081/ (401). Always open /tmp/dsh-ui-url after restart.",
    `# kitPath: ${kitPath}`,
    `$distro = '${distro.replace(/'/g, "''")}'`,
    "function Get-DshTokenUrl {",
    "  $fromFile = (wsl.exe -d $distro -- bash -lc 'cat /tmp/dsh-ui-url 2>/dev/null').Trim()",
    "  if ($fromFile -match 'token=') { return $fromFile }",
    "  return ''",
    "}",
    "function Start-DshWsl {",
    // `&` rather than Start-Process -ArgumentList.
    //
    // Start-Process joins an -ArgumentList array with spaces and quotes nothing,
    // so the command string -- which is full of spaces and semicolons -- arrived
    // at bash as several argv entries and only the tail of it ran. Measured:
    //
    //   Start-Process ... @(..., 'bash', '-lc', 'echo ARG_TEST; echo second; whoami')
    //     -> prints "second" and "rchua"; ARG_TEST never ran
    //   & wsl.exe -d $d -- bash -lc 'echo ARG_TEST; echo second; whoami'
    //     -> prints all three
    //
    // That is why the desktop shortcut did nothing: the recovery path had never
    // worked, and the moment it was needed was the moment everything else was
    // already broken.
    //
    // The console flash is handled on the shortcut instead, where WindowStyle
    // applies to the PowerShell host that owns the window.
    `  & wsl.exe -d $distro -- bash -lc '${psQuote(bashRestart)}'`,
    "  Start-Sleep -Seconds 12",
    "  $url = Get-DshTokenUrl",
    "  if ($url) { Start-Process $url } else { Write-Host 'FAIL: no token URL in /tmp/dsh-ui-url — re-run restart-dsh-web.sh' }",
    "}",
    "function Open-DshUi {",
    "  $url = Get-DshTokenUrl",
    "  if ($url) { Start-Process $url } else {",
    "    Write-Host 'No fresh token — running Start/Restart first…'",
    "    Start-DshWsl",
    "  }",
    "}",
    "function Show-DshHealth {",
    `  & wsl.exe -d $distro -- bash -lc '${psQuote(bashHealth)}'`,
    "}",
    "Start-DshWsl",
    "",
  ].join("\n");
}

export function openUiPs1Body(distro) {
  return [
    "# Generated by dsh-wsl-tray — open ONLY the current token URL (never bare :3081).",
    `$distro = '${distro.replace(/'/g, "''")}'`,
    "$url = (wsl.exe -d $distro -- bash -lc 'cat /tmp/dsh-ui-url 2>/dev/null').Trim()",
    "if ($url -match 'token=') { Start-Process $url }",
    "else {",
    "  Write-Host 'FAIL: /tmp/dsh-ui-url missing or has no token. Run Start / Restart dsh first.'",
    "  Start-Sleep -Seconds 4",
    "}",
    "",
  ].join("\n");
}

export function ahkBody(distro, url, ps1WinPath, kitPath, healthPs1WinPath, openUiPs1WinPath) {
  const ps1Esc = ps1WinPath.replace(/\\/g, "\\\\");
  const healthEsc = (healthPs1WinPath || ps1WinPath).replace(/\\/g, "\\\\");
  const openEsc = (openUiPs1WinPath || ps1WinPath).replace(/\\/g, "\\\\");
  return [
    AHK_HEADER,
    "#Requires AutoHotkey v2.0",
    "#SingleInstance Force",
    `; kitPath: ${kitPath}`,
    "TraySetIcon()",
    "A_TrayMenu.Add('Open dsh web (token URL)', (*) => Run('powershell.exe -NoProfile -ExecutionPolicy Bypass -File \"" +
      openEsc +
      "\"'))",
    "A_TrayMenu.Add('Start / Restart dsh (WSL)', (*) => Run('powershell.exe -NoProfile -ExecutionPolicy Bypass -File \"" +
      ps1Esc +
      "\"'))",
    "A_TrayMenu.Add('Health check', (*) => Run('powershell.exe -NoProfile -ExecutionPolicy Bypass -File \"" +
      healthEsc +
      "\"'))",
    "A_TrayMenu.Add('Quit tray', (*) => ExitApp())",
    "A_TrayMenu.Default := 'Open dsh web (token URL)'",
    "A_TrayMenu.ClickCount := 1",
    `; Distro: ${distro}`,
    "",
  ].join("\n");
}

export function healthPs1Body(distro, kitPath) {
  const health = `${kitPath}/scripts/check-dsh-health.sh`;
  const alive = `${kitPath}/scripts/dsh-web-alive.inc.sh`;
  const bashHealth = `bash '${health}'; echo; read -n 1 -p 'Press any key...'`;
  return [
    "# Generated by dsh-wsl-tray — run kit check-dsh-health.sh inside WSL.",
    `$distro = '${distro.replace(/'/g, "''")}'`,
    // `&`, not Start-Process -ArgumentList: see the note in ps1Body. The array
    // form splits the command string on its own spaces and bash only sees the
    // tail of it.
    `& wsl.exe -d $distro -- bash -lc '${psQuote(bashHealth)}'`,
    "",
    "Read-Host 'Press Enter to close'",
    "",
  ].join("\n");
}

async function detectAutoHotkey() {
  try {
    const { stdout } = await runPowerShell(
      "(Get-Command AutoHotkey64.exe, AutoHotkey.exe -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty Source)",
      { timeoutMs: 8_000 },
    );
    return stdout.trim().split(/\r?\n/).map((s) => s.trim()).find(Boolean) || "";
  } catch {
    return "";
  }
}

async function createDesktopShortcut(startPs1Win) {
  try {
    // The value goes into a single-quoted PowerShell string, so the only
    // character that needs doubling is the single quote itself.
    //
    // It used to double backslashes as well. That was harmless while the
    // argument was a Linux path with none, and wrong the moment it became a UNC
    // path: the shortcut was written with \\\\wsl.localhost\\Ubuntu-24.04\\...,
    // which is not a path any Windows API resolves. The path is only useful if
    // it survives this function byte for byte.
    const arg = String(startPs1Win).replace(/'/g, "''");
    await runPowerShell(
      `$ws = New-Object -ComObject WScript.Shell; $s = $ws.CreateShortcut("$env:USERPROFILE\\Desktop\\DSH WSL.lnk"); $s.TargetPath = 'powershell.exe'; $s.Arguments = '-NoProfile -ExecutionPolicy Bypass -File "' + '${arg}' + '"'; $s.Save()`,
      { timeoutMs: 20_000 },
    );
    return "Desktop\\DSH WSL.lnk";
  } catch {
    return "(shortcut creation failed — use startPs1 manually)";
  }
}

/**
 * A Linux path as something Windows can open.
 *
 * /mnt/c/... becomes C:\. Everything else -- the files this writes live under
 * $HOME/.dsh/tray, which is not on a drive letter -- has to go through the WSL
 * share, because Windows cannot open /home/rchua/... at all. Verified with
 * Test-Path: 'C:\Users\rchua\.dsh\tray\x.ps1' and '/home/rchua/.dsh/tray/x.ps1'
 * both fail; '\\wsl.localhost\<distro>\home\rchua\.dsh\tray\x.ps1' succeeds.
 *
 * This returned such paths unchanged before, and the desktop shortcut was
 * created with -File "/home/rchua/.dsh/tray/start-dsh-web.ps1". The shortcut
 * had never worked: double-clicking it did nothing, which is the worst possible
 * failure for a recovery entry point, because the moment you need it is the
 * moment nothing else works either.
 */
function wslPathToWin(path, distro = distroName()) {
  const drive = path.match(/^\/mnt\/([a-z])\/(.*)$/i);
  if (drive) return `${drive[1].toUpperCase()}:\\${drive[2].replace(/\//g, "\\")}`;
  if (path.startsWith("/")) {
    // UNC, and not \\wsl$ -- the older form works too, but \\wsl.localhost is
    // the one Microsoft documents and the one that resolves without the dollar.
    return `\\\\wsl.localhost\\${distro}${path.replace(/\//g, "\\")}`;
  }
  return path;
}

export async function execute(args) {
  const action = ["install_scripts", "install_tray"].includes(args?.action)
    ? args.action
    : "status";
  const url =
    typeof args?.url === "string" && args.url.trim() ? args.url.trim() : "http://127.0.0.1:3081";
  const distro = distroName();
  const dir = join(homedir(), ".dsh", "tray");
  const startPs1 = join(dir, "start-dsh-web.ps1");
  const healthPs1 = join(dir, "check-dsh-health.ps1");
  const trayAhk = join(dir, "dsh-tray.ahk");
  const kit = resolveKitPath({ kitPath: args?.kitPath });
  const advice = [
    "install_scripts: PowerShell launcher + optional Desktop shortcut.",
    "install_tray: AutoHotkey v2 tray with Open(token) / Restart / Health. Install AHK from https://www.autohotkey.com/ if missing.",
    "Open always uses /tmp/dsh-ui-url (?token=). Bare :3081 is 401 on dsh ≥0.1.2.",
    "Set DSH_WSL_KIT to your dsh-wsl-kit checkout if auto-detect fails.",
    "Run the .ahk once at login, or pin start-dsh-web.ps1 to Task Scheduler.",
  ];
  if (!kit.ok) {
    advice.unshift(
      "dsh-wsl-kit not found — set DSH_WSL_KIT=/path/to/dsh-wsl-kit or pass kitPath=… then re-run install_scripts.",
    );
  }
  if (action === "status") {
    return {
      ok: kit.ok,
      action,
      distro,
      url,
      dir,
      kitPath: kit.path,
      kitSource: kit.source,
      startPs1: existsSync(startPs1) ? startPs1 : "",
      trayAhk: existsSync(trayAhk) ? trayAhk : "",
      advice,
      error: kit.ok ? "" : "kit_path_missing",
    };
  }
  if (!kit.ok) {
    return {
      ok: false,
      action,
      distro,
      url,
      dir,
      kitPath: "",
      advice,
      error: "kit_path_missing",
    };
  }
  mkdirSync(dir, { recursive: true });
  const openUiPs1 = join(dir, "open-dsh-ui.ps1");
  writeFileSync(startPs1, ps1Body(distro, url, kit.path), "utf8");
  writeFileSync(healthPs1, healthPs1Body(distro, kit.path), "utf8");
  writeFileSync(openUiPs1, openUiPs1Body(distro), "utf8");
  const shortcutHint = await createDesktopShortcut(wslPathToWin(startPs1, distro));
  let autohotkeyPath = "";
  if (action === "install_tray") {
    const ps1Win = wslPathToWin(startPs1);
    const healthWin = wslPathToWin(healthPs1);
    const openWin = wslPathToWin(openUiPs1);
    writeFileSync(trayAhk, ahkBody(distro, url, ps1Win, kit.path, healthWin, openWin), "utf8");
    autohotkeyPath = await detectAutoHotkey();
    if (autohotkeyPath) {
      advice.unshift(`Double-click ${trayAhk} or run: "${autohotkeyPath}" "${wslPathToWin(trayAhk)}"`);
    } else {
      advice.unshift("AutoHotkey not found on Windows PATH — install v2, then double-click dsh-tray.ahk.");
    }
  }
  return {
    ok: true,
    action,
    distro,
    url,
    dir,
    kitPath: kit.path,
    kitSource: kit.source,
    startPs1,
    healthPs1,
    openUiPs1,
    trayAhk: action === "install_tray" ? trayAhk : "",
    autohotkeyPath,
    shortcutHint,
    advice,
  };
}
