import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { distroName, runPowerShell } from "./wsl-host.js";

export function notWsl() {
  return { ok: false, error: "not running in WSL" };
}

export function parameters() {
  return {
    type: "object",
    additionalProperties: false,
    properties: {
      action: {
        type: "string",
        enum: ["status", "install_scripts"],
        description: "status = report paths; install_scripts = write launcher scripts under ~/.dsh/tray.",
      },
      url: { type: "string", description: "dsh web URL (default http://127.0.0.1:3080)." },
    },
  };
}

export function outputSchema() {
  return { type: "object", additionalProperties: true };
}

export function format(v) {
  const lines = [`wsl_tray action=${v.action || "?"} ok=${v.ok}`];
  if (v.dir) lines.push(`dir: ${v.dir}`);
  if (v.startPs1) lines.push(`startPs1: ${v.startPs1}`);
  if (v.shortcutHint) lines.push(`shortcut: ${v.shortcutHint}`);
  for (const a of v.advice || []) lines.push(`- ${a}`);
  if (v.error) lines.push(`error: ${v.error}`);
  return lines.join("\n");
}

export async function execute(args) {
  const action = args?.action === "install_scripts" ? "install_scripts" : "status";
  const url = typeof args?.url === "string" && args.url.trim() ? args.url.trim() : "http://127.0.0.1:3080";
  const distro = distroName();
  const dir = join(homedir(), ".dsh", "tray");
  const startPs1 = join(dir, "start-dsh-web.ps1");
  const advice = [
    "Create a Windows shortcut to powershell.exe -NoProfile -File <startPs1> for one-click start.",
    "For a real system-tray icon, wrap the same script with a small AutoHotkey/WinForms host later.",
  ];
  if (action === "status") {
    return {
      ok: true,
      action,
      distro,
      url,
      dir,
      startPs1: existsSync(startPs1) ? startPs1 : "",
      advice,
    };
  }
  mkdirSync(dir, { recursive: true });
  const body = [
    "# Generated by dsh-wsl-tray — start dsh web inside WSL and open the Windows browser.",
    `$distro = '${distro.replace(/'/g, "''")}'`,
    `$url = '${url.replace(/'/g, "''")}'`,
    "Start-Process wsl.exe -ArgumentList @('-d', $distro, '--', 'bash', '-lc', 'export PATH=\"$HOME/.local/bin:/usr/local/bin:$PATH\"; exec dsh web --no-open') -WindowStyle Hidden",
    "Start-Sleep -Seconds 2",
    "Start-Process $url",
    "",
  ].join("\n");
  writeFileSync(startPs1, body, "utf8");
  let shortcutHint = "";
  try {
    await runPowerShell(
      `$ws = New-Object -ComObject WScript.Shell; $s = $ws.CreateShortcut(\"$env:USERPROFILE\\Desktop\\DSH WSL.lnk\"); $s.TargetPath = 'powershell.exe'; $s.Arguments = '-NoProfile -ExecutionPolicy Bypass -File \"${startPs1.replace(/\\/g, "\\\\")}\"'; $s.Save()`,
      { timeoutMs: 20_000 },
    );
    shortcutHint = "Desktop\\DSH WSL.lnk";
  } catch {
    shortcutHint = "(shortcut creation failed — use startPs1 manually)";
  }
  return { ok: true, action, distro, url, dir, startPs1, shortcutHint, advice };
}
