import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { distroName, runPowerShell } from "./wsl-host.js";

const AHK_HEADER = "; Generated by dsh-wsl-tray — requires AutoHotkey v2+";

export function notWsl() {
  return { ok: false, error: "not running in WSL" };
}

export function parameters() {
  return {
    type: "object",
    additionalProperties: false,
    properties: {
      action: {
        type: "string",
        enum: ["status", "install_scripts", "install_tray"],
        description:
          "status = report paths; install_scripts = PS1 + desktop shortcut; install_tray = AHK v2 tray icon + PS1.",
      },
      url: { type: "string", description: "Browser URL (default http://127.0.0.1:3081 via kit relay; dsh itself listens on 3080 inside WSL)." },
    },
  };
}

export function outputSchema() {
  return { type: "object", additionalProperties: true };
}

export function format(v) {
  const lines = [`wsl_tray action=${v.action || "?"} ok=${v.ok}`];
  if (v.dir) lines.push(`dir: ${v.dir}`);
  if (v.startPs1) lines.push(`startPs1: ${v.startPs1}`);
  if (v.trayAhk) lines.push(`trayAhk: ${v.trayAhk}`);
  if (v.autohotkeyPath) lines.push(`autohotkey: ${v.autohotkeyPath}`);
  if (v.shortcutHint) lines.push(`shortcut: ${v.shortcutHint}`);
  for (const a of v.advice || []) lines.push(`- ${a}`);
  if (v.error) lines.push(`error: ${v.error}`);
  return lines.join("\n");
}

function ps1Body(distro, url) {
  // dsh only allows 127.0.0.1 (not 0.0.0.0). Kit restart script starts dsh:3080 + IPv6 relay:3081.
  const bashLc =
    "export PATH=$HOME/.local/bin:/usr/local/bin:$PATH; " +
    "sed 's/\\r$//' /mnt/c/Users/rchua/Desktop/AIFullStackDevelopment/dsh-wsl-kit/scripts/restart-dsh-web.sh > /tmp/restart-dsh-web.sh; " +
    "bash /tmp/restart-dsh-web.sh";
  const openUrl = typeof url === "string" && url.includes("3080")
    ? url.replace("3080", "3081")
    : (url || "http://127.0.0.1:3081");
  return [
    "# Generated by dsh-wsl-tray — start dsh web (WSL) + localhost relay, then open Windows browser.",
    "# Open http://127.0.0.1:3081 — NOT :3000 (GenericAgent) and not raw :3080 (WSL-only bind).",
    `$distro = '${distro.replace(/'/g, "''")}'`,
    `$url = '${openUrl.replace(/'/g, "''")}'`,
    `Start-Process wsl.exe -ArgumentList @('-d', $distro, '--', 'bash', '-lc', '${bashLc}') -WindowStyle Hidden`,
    "Start-Sleep -Seconds 8",
    "Start-Process $url",
    "",
  ].join("\n");
}

function ahkBody(distro, url, ps1WinPath) {
  const ps1Esc = ps1WinPath.replace(/\\/g, "\\\\");
  return [
    AHK_HEADER,
    "#Requires AutoHotkey v2.0",
    "#SingleInstance Force",
    "TraySetIcon()",
    "A_TrayMenu.Add('Open dsh web', (*) => Run('explorer.exe " + url.replace(/"/g, '""') + "'))",
    "A_TrayMenu.Add('Start dsh (WSL)', (*) => Run('powershell.exe -NoProfile -ExecutionPolicy Bypass -File \"" + ps1Esc + "\"'))",
    "A_TrayMenu.Add('Quit tray', (*) => ExitApp())",
    "A_TrayMenu.Default := 'Open dsh web'",
    "A_TrayMenu.ClickCount := 1",
    `; Distro: ${distro}`,
    "",
  ].join("\n");
}

async function detectAutoHotkey() {
  try {
    const { stdout } = await runPowerShell(
      "(Get-Command AutoHotkey64.exe, AutoHotkey.exe -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty Source)",
      { timeoutMs: 8_000 },
    );
    return stdout.trim().split(/\r?\n/).map((s) => s.trim()).find(Boolean) || "";
  } catch {
    return "";
  }
}

async function createDesktopShortcut(startPs1) {
  try {
    await runPowerShell(
      `$ws = New-Object -ComObject WScript.Shell; $s = $ws.CreateShortcut(\"$env:USERPROFILE\\Desktop\\DSH WSL.lnk\"); $s.TargetPath = 'powershell.exe'; $s.Arguments = '-NoProfile -ExecutionPolicy Bypass -File \"${startPs1.replace(/\\/g, "\\\\")}\"'; $s.Save()`,
      { timeoutMs: 20_000 },
    );
    return "Desktop\\DSH WSL.lnk";
  } catch {
    return "(shortcut creation failed — use startPs1 manually)";
  }
}

function wslPathToWin(path) {
  const m = path.match(/^\/mnt\/([a-z])\/(.*)$/i);
  if (!m) return path;
  return `${m[1].toUpperCase()}:\\${m[2].replace(/\//g, "\\")}`;
}

export async function execute(args) {
  const action = ["install_scripts", "install_tray"].includes(args?.action)
    ? args.action
    : "status";
  const url = typeof args?.url === "string" && args.url.trim() ? args.url.trim() : "http://127.0.0.1:3081";
  const distro = distroName();
  const dir = join(homedir(), ".dsh", "tray");
  const startPs1 = join(dir, "start-dsh-web.ps1");
  const trayAhk = join(dir, "dsh-tray.ahk");
  const advice = [
    "install_scripts: PowerShell launcher + optional Desktop shortcut.",
    "install_tray: AutoHotkey v2 tray (right-click menu). Install AHK from https://www.autohotkey.com/ if missing.",
    "Run the .ahk once at login, or pin start-dsh-web.ps1 to Task Scheduler.",
  ];
  if (action === "status") {
    return {
      ok: true,
      action,
      distro,
      url,
      dir,
      startPs1: existsSync(startPs1) ? startPs1 : "",
      trayAhk: existsSync(trayAhk) ? trayAhk : "",
      advice,
    };
  }
  mkdirSync(dir, { recursive: true });
  writeFileSync(startPs1, ps1Body(distro, url), "utf8");
  const shortcutHint = await createDesktopShortcut(startPs1);
  let autohotkeyPath = "";
  if (action === "install_tray") {
    const ps1Win = wslPathToWin(startPs1);
    writeFileSync(trayAhk, ahkBody(distro, url, ps1Win), "utf8");
    autohotkeyPath = await detectAutoHotkey();
    if (autohotkeyPath) {
      advice.unshift(`Double-click ${trayAhk} or run: "${autohotkeyPath}" "${wslPathToWin(trayAhk)}"`);
    } else {
      advice.unshift("AutoHotkey not found on Windows PATH — install v2, then double-click dsh-tray.ahk.");
    }
  }
  return {
    ok: true,
    action,
    distro,
    url,
    dir,
    startPs1,
    trayAhk: action === "install_tray" ? trayAhk : "",
    autohotkeyPath,
    shortcutHint,
    advice,
  };
}
